export const el = {
    coreToggle: document.getElementById('coreToggle'),
    coreItems: Array.from(document.querySelectorAll('#coreToggle .labels [data-core]')),
    outBlock: document.getElementById('outBlock'),
    errorBlock: document.getElementById('errorBlock'),
    errorText: document.getElementById('errorText'),
    links: document.getElementById('links'),
    tunName: document.getElementById('tunName'),
    urlTestButton: document.getElementById('urlTestButton'),
    urlTestMenu: document.getElementById('urlTestMenu'),
    gen: document.getElementById('gen'),
    btnCopy: document.getElementById('btnCopy'),
    btnDownload: document.getElementById('btnDownload'),
    cbTun: document.getElementById('cbTun'),
    cbSocks: document.getElementById('cbSocks'),
    cbExtended: document.getElementById('cbExtended'),
    cbClashSecret: document.getElementById('cbClashSecret'),
    cbMihomoSub: document.getElementById('cbMihomoSub'),
    cbMihomoSocks: document.getElementById('cbMihomoSocks'),
    cbMihomoTun: document.getElementById('cbMihomoTun'),
    cbMihomoPerProxyTun: document.getElementById('cbMihomoPerProxyTun'),
    cbMihomoPerProxyPort: document.getElementById('cbMihomoPerProxyPort'),
    cbMihomoWebUI: document.getElementById('cbMihomoWebUI'),
    cbDetour: document.getElementById('cbDetour'),
    lblMihomoSub: document.getElementById('lblMihomoSub'),
    lblMihomoSocks: document.getElementById('lblMihomoSocks'),
    lblMihomoTun: document.getElementById('lblMihomoTun'),
    lblMihomoPerProxyTun: document.getElementById('lblMihomoPerProxyTun'),
    lblMihomoPerProxyPort: document.getElementById('lblMihomoPerProxyPort'),
    lblMihomoWebUI: document.getElementById('lblMihomoWebUI'),
    cbXrayBalancer: document.getElementById('cbXrayBalancer'),
    lblXrayBalancer: document.getElementById('lblXrayBalancer'),
    cbXrayTun: document.getElementById('cbXrayTun'),
    lblXrayTun: document.getElementById('lblXrayTun'),
    cbXraySocks: document.getElementById('cbXraySocks'),
    lblXraySocks: document.getElementById('lblXraySocks'),
    cbPerTunMixed: document.getElementById('cbPerTunMixed'),
    lblPerTunMixed: document.getElementById('lblPerTunMixed'),
    cbAndroidMode: document.getElementById('cbAndroidMode'),
    lblAndroidMode: document.getElementById('lblAndroidMode'),
    lblDetour: document.getElementById('lblDetour'),
    out: document.getElementById('out'),
    btnChevron: document.getElementById('btnChevron'),
    settingsPanel: document.getElementById('settingsPanel'),
    btnWgUpload: document.getElementById('btnWgUpload'),
    wgFile: document.getElementById('wgFile'),
};

export const header = document.getElementById('asciiHeader');
